name: development

on:
  push:
    branches-ignore:
      - 'release/**'

env:
  DOTNET_VERSION: '8.x'
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          cache: true
          cache-dependency-path: '**/packages.lock.json'
      - run: |
          dotnet restore --use-lock-file --locked-mode
      - run: |
          dotnet build --configuration Release --no-restore
      - run: |
          dotnet test --logger trx --results-directory dotnet-test-results
      - uses: actions/upload-artifact@v4
        with:
            name: dotnet-test-results
            path: dotnet-test-results
            retention-days: 7